# Generated by Django 3.1.1 on 2020-10-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('boloindya_id', models.IntegerField(blank=True, null=True, verbose_name='BoloIndya ID')),
                ('payment_method', models.CharField(choices=[('paytm_wallet', 'PayTM Wallet'), ('upi', 'UPI'), ('account_transfer', 'Bank Account Transfer')], max_length=20, verbose_name='Payment Method')),
                ('paytm_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Paytm Number')),
                ('upi', models.CharField(blank=True, max_length=50, null=True, verbose_name='UIP')),
                ('account_number', models.IntegerField(blank=True, null=True, verbose_name='Account Number')),
                ('bank_ifsc', models.CharField(blank=True, max_length=30, null=True, verbose_name='Bank IFSC')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
        ),
    ]
