# Generated by Django 3.1.1 on 2020-10-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_beneficiary_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='verification_txn_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Verification TXN ID'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='upi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UPI'),
        ),
    ]
