# Generated by Django 3.1.1 on 2020-10-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20201002_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('boloindya_id', models.IntegerField(default=0, verbose_name='BoloIndya ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('video_count', models.IntegerField(default=0, verbose_name='Video Count')),
                ('follower_count', models.IntegerField(default=0, verbose_name='Follower Count')),
                ('playtime', models.FloatField(default=0, verbose_name='Playtime Count')),
                ('view_count', models.IntegerField(default=0, verbose_name='View Count')),
            ],
        ),
    ]
