# Generated by Django 3.1.1 on 2020-10-03 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_topuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuser',
            name='agg_month',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 12, 25, 35, 864387, tzinfo=utc), verbose_name='Agg Month'),
            preserve_default=False,
        ),
    ]
