# Generated by Django 3.1.1 on 2020-10-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_topuser_agg_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuser',
            name='agg_month',
            field=models.DateField(verbose_name='Agg Month'),
        ),
    ]
