# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-06 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20201003_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number'),
        ),
    ]
