# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-06 21:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0007_auto_20201006_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_beneficiary', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modified_beneficiary', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
