# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-06 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_auto_20201006_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='beneficiary_type',
            field=models.CharField(choices=[(b'emp_salary', b'Employee Salary'), (b'creator_payout', b'Creator Payout')], default=b'creator_payout', max_length=30, verbose_name='Beneficiary Type'),
        ),
    ]
