# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-07 15:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0009_beneficiary_beneficiary_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBeneficiary',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('boloindya_id', models.IntegerField(blank=True, null=True, verbose_name='BoloIndya ID')),
                ('payment_method', models.CharField(choices=[(b'paytm_wallet', b'PayTM Wallet'), (b'upi', b'UPI'), (b'account_transfer', b'Bank Account Transfer')], max_length=20, verbose_name='Payment Method')),
                ('paytm_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Paytm Number')),
                ('upi', models.CharField(blank=True, max_length=50, null=True, verbose_name='UPI')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number')),
                ('bank_ifsc', models.CharField(blank=True, max_length=30, null=True, verbose_name='Bank IFSC')),
                ('verification_status', models.CharField(choices=[(b'pending', b'Pending'), (b'verified', b'Verified'), (b'failed', b'Failed')], default=b'pending', max_length=30, verbose_name='Bank IFSC')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('verification_txn_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Verification TXN ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('beneficiary_type', models.CharField(choices=[(b'emp_salary', b'Employee Salary'), (b'creator_payout', b'Creator Payout')], default=b'creator_payout', max_length=30, verbose_name='Beneficiary Type')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical beneficiary',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
