# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-11 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_auto_20201211_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuser',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='Like Count'),
        ),
    ]
