# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-11 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0012_topuser_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
        migrations.AddField(
            model_name='historicalbeneficiary',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
    ]
