# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-31 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncashableDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('duration_start_date', models.DateField(blank=True, null=True, verbose_name='Duration Start Date')),
                ('duration_end_date', models.DateField(blank=True, null=True, verbose_name='Duration End Date')),
                ('bolo_score_earned', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Bolo Scores Earned')),
                ('is_encashed', models.BooleanField(default=False, verbose_name='Is Encashed?')),
                ('enchashed_on', models.DateTimeField(blank=True, null=True)),
                ('is_eligible_for_encash', models.BooleanField(default=False, verbose_name='Is Eligible For Encash?')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_payment_encashabledetail_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EncashableDetail',
                'verbose_name_plural': "EncashableDetail's",
            },
        ),
        migrations.CreateModel(
            name='PaymentCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_type', models.CharField(blank=True, choices=[('1', 'Day'), ('2', 'Week'), ('3', 'Month'), ('4', 'Year')], max_length=10, null=True, verbose_name='Duration Type')),
                ('duration_period', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration Period')),
                ('duration_start_date', models.DateField(blank=True, null=True, verbose_name='Duration Start Date')),
                ('minimum_bolo_score', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Minimum Bolo Score For Eligibility')),
            ],
            options={
                'verbose_name': 'PaymentCycle',
                'verbose_name_plural': "PaymentCycle's",
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('transaction_method', models.CharField(blank=True, choices=[('1', 'Bank Account'), ('2', 'Paytm')], default='2', max_length=10, null=True, verbose_name='Transaction Method')),
                ('transaction_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction Number')),
                ('encashble_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_payment.EncashableDetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_payment_paymentinfo_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PaymentInfo',
                'verbose_name_plural': "PaymentInfo's",
            },
        ),
    ]
