# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-02 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encashabledetail',
            name='bolo_score_details',
            field=models.TextField(blank=True, null=True, verbose_name='Bolo Score Details'),
        ),
    ]
