# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-06 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_payment', '0004_auto_20190904_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='encashabledetail',
            name='equivalent_INR',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Equivalnet INR'),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='enchashable_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_payment.EncashableDetail'),
        ),
    ]
