# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-09 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_payment', '0005_auto_20190906_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcycle',
            name='minimum_bolo_score',
        ),
        migrations.AddField(
            model_name='encashabledetail',
            name='encashable_cycle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Encash Cycle'),
        ),
    ]
