# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-01 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_payment', '0006_auto_20190909_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='encashabledetail',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='Is Expired?'),
        ),
    ]
