# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_auto_20201107_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('enable_time', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=200, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cta', to='advertisement.Ad')),
            ],
        ),
    ]
