# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-07 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_product_discount_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_quantity_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
