# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-08 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_product_max_quantity_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('shop_now', 'Shop Now'), ('install_now', 'Install Now')], default='shop_now', max_length=25),
        ),
        migrations.AlterField(
            model_name='ad',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
