# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-07 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_auto_20201107_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state_id',
            new_name='state',
        ),
    ]
