# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-08 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_auto_20201108_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_gateway_order_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Card')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
