# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-08 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0012_auto_20201108_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
