# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-09 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_auto_20201108_1723'),
        ('advertisement', '0013_order_order_number'),
    ]

    operations = [
    ]
