# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-11 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0015_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='advertisement.Product'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
