# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-10 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0015_clicked_playtime_seen_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicked',
            name='cta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('install', 'Install'), ('shop_now', 'Shop Now')], max_length=25),
        ),
    ]
