# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-12 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0016_auto_20201110_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='draft', max_length=25),
        ),
    ]
