# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-11 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0016_auto_20201111_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cta',
            name='title',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_for_approval', 'Pending for Approval'), ('accepted_by_vender', 'Accepted by vendor'), ('delivered', 'Delivered')], default='skip', max_length=200),
        ),
    ]
