# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-11 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0016_auto_20201110_2325'),
        ('advertisement', '0017_auto_20201111_1411'),
    ]

    operations = [
    ]
