# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-12 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0018_merge_20201111_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('install_now', 'Install Now'), ('shop_now', 'Shop Now'), ('learn_more', 'Learn More')], default='shop_now', max_length=25),
        ),
        migrations.AlterField(
            model_name='ad',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='draft', max_length=25),
        ),
        migrations.AlterField(
            model_name='cta',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
