# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-14 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0019_auto_20201112_1436'),
        ('advertisement', '0021_auto_20201112_1732'),
    ]

    operations = [
    ]
