# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-24 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0022_merge_20201114_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('product_qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('igst_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=10)),
                ('net_amount_payble', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_mode', models.TextField(blank=True, null=True)),
                ('unit_discount', models.PositiveIntegerField(default=0)),
                ('invoice_pdf_url', models.TextField(blank=True, null=True)),
                ('invoice_number', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='is_invoice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='advertisement.Order'),
        ),
    ]
