# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-20 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisement', '0024_auto_20201117_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='poc_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to=settings.AUTH_USER_MODEL),
        ),
    ]
