# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-26 01:33
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations, models
from django.db import connections


def index_entries(apps, schema_editor):
    cursor = connections['default'].cursor()
    cursor.execute("""
        UPDATE advertisement_order 
        SET body_text = to_tsvector('english', coalesce(advertisement_address.name,'') || ' ' || coalesce(advertisement_address.mobile,'') || ' ' || coalesce(advertisement_address.email,''))
        from advertisement_address
        where advertisement_address.id = advertisement_order.shipping_address_id
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0026_order_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='body_text',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.RunPython(index_entries),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('order_placed', 'Order Placed'), ('shipped', 'Shipped'), ('out_of_stock', 'Out of Stock'), ('returned', 'Returned'), ('delivered', 'Delivered')], default='draft', max_length=20),
        ),
    ]
