# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-26 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0027_auto_20201126_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('order_placed', 'Order Placed'), ('shipped', 'Shipped'), ('out_of_stock', 'Out of Stock'), ('returned', 'Returned'), ('delivered', 'Delivered'), ('pending_for_approval', 'Pending for Approval'), ('accepted_by_vender', 'Accepted by vendor')], default='draft', max_length=20),
        ),
    ]
