# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-27 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0023_auto_20201124_1421'),
        ('advertisement', '0028_auto_20201126_1750'),
    ]

    operations = [
    ]
