# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-28 19:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0030_ad_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=['0'], null=True, size=None),
        ),
    ]
