# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-14 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0031_auto_20201128_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicked',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicked', to='advertisement.Ad'),
        ),
        migrations.AlterField(
            model_name='install',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='install', to='advertisement.Ad'),
        ),
        migrations.AlterField(
            model_name='learnmore',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnmore', to='advertisement.Ad'),
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeorder', to='advertisement.Ad'),
        ),
        migrations.AlterField(
            model_name='playtime',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playtime', to='advertisement.Ad'),
        ),
        migrations.AlterField(
            model_name='seen',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen', to='advertisement.Ad'),
        ),
        migrations.AlterField(
            model_name='shopnow',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopnow', to='advertisement.Ad'),
        ),
        migrations.AlterField(
            model_name='skipped',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skipped', to='advertisement.Ad'),
        ),
    ]
