# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-17 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0033_fullwatched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clicked',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='clicked',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playtime',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='playtime',
            name='user',
        ),
        migrations.AddField(
            model_name='fullwatched',
            name='playtime',
            field=models.PositiveIntegerField(default=0, verbose_name='Playtime'),
        ),
        migrations.AddField(
            model_name='install',
            name='playtime',
            field=models.PositiveIntegerField(default=0, verbose_name='Playtime'),
        ),
        migrations.AddField(
            model_name='learnmore',
            name='playtime',
            field=models.PositiveIntegerField(default=0, verbose_name='Playtime'),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='playtime',
            field=models.PositiveIntegerField(default=0, verbose_name='Playtime'),
        ),
        migrations.AddField(
            model_name='seen',
            name='playtime',
            field=models.PositiveIntegerField(default=0, verbose_name='Playtime'),
        ),
        migrations.AddField(
            model_name='shopnow',
            name='playtime',
            field=models.PositiveIntegerField(default=0, verbose_name='Playtime'),
        ),
        migrations.AddField(
            model_name='skipped',
            name='playtime',
            field=models.PositiveIntegerField(default=0, verbose_name='Playtime'),
        ),
        migrations.DeleteModel(
            name='Clicked',
        ),
        migrations.DeleteModel(
            name='Playtime',
        ),
    ]
