# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-28 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0035_ad_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='creator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
