# Generated by Django 3.1.1 on 2020-10-01 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('timeout', 'Timeout'), ('success', 'Success'), ('failed', 'Failed')], default='draft', max_length=20, verbose_name='State')),
                ('pg_state', models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=20, null=True, verbose_name='State')),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Transaction ID')),
                ('payment_gateway_response', jsonfield.fields.JSONField(default=dict, verbose_name='Payment Gateway Response')),
                ('translation_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Transaction DateTime')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation', to='partner.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('timeout', 'Timeout'), ('success', 'Success'), ('failed', 'Failed')], default='draft', max_length=20, verbose_name='State')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='DateTime')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='payout.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionPGState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='draft', max_length=20, verbose_name='State')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='DateTime')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_states', to='payout.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('payment_date', models.IntegerField(verbose_name='Payment Day')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='Modified at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_payments', to='partner.beneficiary')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
