# Generated by Django 3.1.1 on 2020-10-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='translation_datetime',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=1000, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True, verbose_name='Transaction DateTime'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pg_state',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=20, null=True, verbose_name='PG State'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('timeout', 'Timeout'), ('success', 'Success'), ('failed', 'Failed'), ('cancel', 'Cancelled')], default='draft', max_length=20, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='transactionstate',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('timeout', 'Timeout'), ('success', 'Success'), ('failed', 'Failed'), ('cancel', 'Cancelled')], default='draft', max_length=20, verbose_name='State'),
        ),
    ]
