# Generated by Django 3.1.1 on 2020-10-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0002_auto_20201002_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpayment',
            name='added_for_payment',
            field=models.BooleanField(default=False, verbose_name='Added for Payment'),
        ),
    ]
