# Generated by Django 3.1.1 on 2020-10-02 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0003_scheduledpayment_added_for_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionpgstate',
            old_name='translation',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='transactionstate',
            old_name='translation',
            new_name='transaction',
        ),
    ]
