# Generated by Django 3.1.1 on 2020-10-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0004_auto_20201002_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Transaction DateTime'),
        ),
    ]
