# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-26 23:57
from __future__ import unicode_literals

from django.db import migrations
from drf_spirit.utils import generate_refer_earn_code
from forum.user.models import UserProfile,ReferralCode

def run():
    all_profile = UserProfile.objects.filter(is_test_user=False)
    total_count = len(all_profile)
    counter = 1
    for each_profile in all_profile:
        #print "###################",counter," / ",total_count,"#################",created_counter
        counter+=1
        referral_obj,is_created = ReferralCode.objects.get_or_create(for_user=each_profile.user,purpose='refer_n_earn',is_refer_earn_code=True)
        if is_created:
            referral_obj.code=generate_refer_earn_code()
            referral_obj.save()
