# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-09 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='thumbnail_img_url',
            field=models.TextField(default=''),
        ),
    ]
