# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-10 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_available_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingslot',
            name='channel_id',
            field=models.TextField(null=True),
        ),
    ]
