# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-11 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookingslot_channel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='available_slots',
        ),
        migrations.AlterField(
            model_name='bookingslot',
            name='channel_id',
            field=models.TextField(default=uuid.uuid4, null=True),
        ),
    ]
