# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-11 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20201011_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingslot',
            name='channel_id',
            field=models.TextField(default=uuid.uuid4),
        ),
    ]
