# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-11 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0006_auto_20201011_1403'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbooking',
            unique_together=set([('user', 'booking_slot')]),
        ),
    ]
