# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-16 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_appconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='profile_pic_img_url',
            field=models.TextField(default=''),
        ),
    ]
