# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-16 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20201016_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayOutConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_for_popular', models.CharField(max_length=10)),
                ('commission_default', models.CharField(max_length=10)),
                ('tnc_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
