# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-17 21:26
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0022_auto_20200709_1303'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_topic', '0119_auto_20200916_0028'),
        ('booking', '0011_payoutconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner_img_url', models.TextField(blank=True, null=True)),
                ('thumbnail_img_url', models.TextField(blank=True, null=True)),
                ('profile_pic_img_url', models.TextField(blank=True, null=True)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('language_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('is_approved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_events', to='forum_category.Category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('hash_tags', models.ManyToManyField(blank=True, null=True, related_name='hash_tag_events', to='forum_topic.TongueTwister')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('0', 'Draft'), ('1', 'Booked'), ('2', 'Cancelled')], default='0', max_length=10)),
                ('payment_status', models.CharField(choices=[('0', 'Pending'), ('1', 'Success'), ('2', 'Failed')], default='0', max_length=10)),
                ('booking_id', models.TextField(blank=True, null=True)),
                ('transaction_id', models.TextField(blank=True, null=True)),
                ('payment_method', models.TextField(blank=True, default='RazorPay', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_event_bookings', to='booking.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('channel_id', models.TextField(blank=True, default=uuid.uuid4, null=True)),
                ('state', models.CharField(blank=True, choices=[('0', 'Available'), ('1', 'Booked')], default='0', max_length=10, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_slot', to='booking.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='event_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_slot_event_bookings', to='booking.EventSlot'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
