# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-17 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20201017_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventbooking',
            old_name='booking_id',
            new_name='payment_gateway_order_id',
        ),
    ]
