# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-18 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20201018_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventslot',
            name='state',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=10, null=True),
        ),
    ]
