# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-19 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20201018_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='category',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hash_tags',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='language_ids',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='profile_pic_img_url',
        ),
    ]
