# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-19 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20201019_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='draft', max_length=25),
        ),
        migrations.AlterField(
            model_name='eventslot',
            name='state',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('booked', 'Booked'), ('hold', 'Hold')], default='available', max_length=25, null=True),
        ),
    ]
