# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-20 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='booking_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='payment_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='draft', max_length=25),
        ),
    ]
