# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-26 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20201020_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
