# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-30 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_auto_20201030_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='payment_mode',
            field=models.CharField(choices=[('card', 'Card')], default='card', max_length=25),
        ),
    ]
