# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-31 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_eventbooking_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbookinginvoice',
            name='invoice_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
