# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-20 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_eventbookinginvoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('all', 'ALL'), ('trending', 'Trending'), ('recomended', 'Recomended')], default='all', max_length=25, null=True),
        ),
    ]
