# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-23 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_landscape_img_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
