# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-05 15:58
from __future__ import unicode_literals

from django.db import migrations

from connection import dynamo_client
from booking.models import EventBookingEvent

client = dynamo_client()

def create_dynamo_table(apps, schema_editor):
    response = client.create_table(
        TableName=EventBookingEvent,
        AttributeDefinitions=[
            {
                'AttributeName': 'event',
                'AttributeType': 'S'
            },
            {
                'AttributeName': 'id',
                'AttributeType': 'N'
            },
        ],
        KeySchema=[
            {
                'AttributeName': 'event',
                'KeyType': 'HASH'
            },
            {
                'AttributeName': 'id',
                'KeyType': 'RANGE'
            }
        ],
        BillingMode='PAY_PER_REQUEST',
    )
    print "response", response

class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_event_banner_landscape_img_url'),
    ]

    operations = [
        migrations.RunPython(create_dynamo_table),
    ]
