# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0010_remove_category_category_order'),
        ('forum_user', '0009_auto_20161114_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.CharField(blank=True, max_length=500, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=300, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extra_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('0', 'English'), ('1', 'Hindi'), ('2', 'Tamil'), ('3', 'Telgu')], default='0', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Profile Pic'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='refrence',
            field=models.CharField(blank=True, choices=[('0', 'native'), ('1', 'facebook')], default='0', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sub_category',
            field=models.ManyToManyField(related_name='forum_user_userprofile_sub_category', to='forum_category.Category', verbose_name='Sub Category'),
        ),
    ]
