# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0012_auto_20190423_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile No'),
        ),
    ]
