# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0014_auto_20190504_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('app_version', models.CharField(blank=True, max_length=100, verbose_name='Version')),
            ],
            options={
                'verbose_name_plural': 'AppVersions',
            },
        ),
    ]
