# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0015_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='is_hard_push',
            field=models.BooleanField(default=False),
        ),
    ]
