# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0016_appversion_is_hard_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='changes',
            field=models.TextField(blank=True, null=True, verbose_name='Changes'),
        ),
        migrations.AddField(
            model_name='appversion',
            name='changes_title',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Changes Title'),
        ),
    ]
