# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0017_auto_20190509_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('1', 'English'), ('2', 'Hindi'), ('3', 'Tamil'), ('4', 'Telgu')], default='0', max_length=10, null=True),
        ),
    ]
