# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0019_auto_20190515_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_geo_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lang',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Langitude'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Latitude'),
        ),
    ]
