# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0020_auto_20190521_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='click_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Click Id'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='click_id_response',
            field=models.TextField(blank=True, null=True, verbose_name='Click Id Response'),
        ),
    ]
