# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-17 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0022_userprofile_is_test_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vb_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
