# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0023_userprofile_vb_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_expert',
            field=models.BooleanField(default=False, verbose_name='expert status'),
        ),
    ]
