# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0024_userprofile_is_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='d_o_b',
            field=models.CharField(blank=True, max_length=100, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], default='', max_length=10, null=True),
        ),
    ]
