# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-05 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0026_androidlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidlogs',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='st_logs', to=settings.AUTH_USER_MODEL, verbose_name='profile'),
        ),
    ]
