# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-08 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0029_referralcode_referralcodeused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='for_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referralcodeused',
            name='by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
