# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0030_auto_20190808_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcodeused',
            name='is_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='referralcodeused',
            name='by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
