# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 01:40
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0031_auto_20190809_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppagecontent',
            name='page_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Page Description'),
        ),
    ]
