# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0032_auto_20190812_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
