# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0033_userprofile_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ref Code'),
        ),
        #migrations.AddField(
        #    model_name='referralcode',
        #    name='campaign_url',
        #    field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Campaign URL'),
        #),
    ]
