# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0036_auto_20190814_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Instagarm_ID',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instagram ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Twitter URL'),
        ),
    ]
