# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0037_auto_20190819_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Instagarm_ID',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagarm_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='LinkedIn URL'),
        ),
    ]
