# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-30 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0038_auto_20190819_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcodeused',
            name='click_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Click Id'),
        ),
        migrations.AddField(
            model_name='referralcodeused',
            name='pid',
            field=models.CharField(blank=True, max_length=255, verbose_name='PID'),
        ),
        migrations.AddField(
            model_name='referralcodeused',
            name='referral_dump',
            field=models.TextField(blank=True, null=True, verbose_name='Referral Dump'),
        ),
    ]
