# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-31 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0038_auto_20190819_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='encashable_bolo_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
