# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-04 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0039_userprofile_encashable_bolo_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='bolo_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Minimum Bolo Score For Monetize/Bolo Score Equivalent Money'),
        ),
        migrations.AddField(
            model_name='weight',
            name='equivalent_INR',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Bolo Equivalent Money'),
        ),
        migrations.AddField(
            model_name='weight',
            name='is_monetize',
            field=models.BooleanField(default=False),
        ),
    ]
