# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-20 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0039_auto_20190830_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidlogs',
            name='log_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Log Type'),
        ),
    ]
