# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-17 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_user', '0039_auto_20190830_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaAndroidLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoid', models.CharField(db_index=True, max_length=150, verbose_name='videoid')),
                ('timeplayerready', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('timeplay', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
