# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-06 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0040_auto_20190904_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='equivalent_INR',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Bolo Equivalent Money in INR'),
        ),
    ]
