# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-17 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0040_deltaandroidlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltaandroidlogs',
            name='user',
            field=models.CharField(db_index=True, max_length=200, verbose_name='userid'),
        ),
    ]
