# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-01 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0040_androidlogs_log_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='version_to_be_pushed',
            field=models.CharField(blank=True, max_length=100, verbose_name='Version To be Pushed'),
        ),
    ]
