# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-07 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0039_auto_20190830_1256'),
        ('forum_user', '0041_auto_20190906_1243'),
    ]

    operations = [
    ]
