# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-23 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0040_androidlogs_log_type'),
        ('forum_user', '0042_merge_20190907_1316'),
    ]

    operations = [
    ]
