# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-14 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0043_merge_20190923_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPlaytime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='user')),
                ('videoid', models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='videoid')),
                ('duration', models.PositiveIntegerField(default=0, editable=False, verbose_name='duration')),
            ],
        ),
    ]
