# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-01 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0043_merge_20190923_1327'),
        ('forum_user', '0041_appversion_version_to_be_pushed'),
    ]

    operations = [
    ]
