# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-10 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0044_merge_20191001_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_dark_mode_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
