# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0045_auto_20191015_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocompleterate',
            name='percentage_viewed',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='percentage_viewed'),
        ),
    ]
