# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-21 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0045_userprofile_is_dark_mode_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcodeused',
            name='android_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='android_id'),
        ),
    ]
