# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-16 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0046_auto_20191015_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppTimeSpend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=250, null=True, verbose_name='user')),
                ('total_time', models.PositiveIntegerField(default=0, editable=False, verbose_name='totaltime')),
            ],
        ),
    ]
