# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-18 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0047_userapptimespend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapptimespend',
            name='total_time',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='totaltime'),
        ),
    ]
