# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-18 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0048_auto_20191018_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoplaytime',
            name='timestamp',
            field=models.DateTimeField(null=True, verbose_name='timestamp'),
        ),
    ]
