# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-23 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0050_videocompleterate_timestamp'),
        ('forum_user', '0046_referralcodeused_android_id'),
    ]

    operations = [
    ]
