# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-25 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0051_merge_20191023_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
