# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-03 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0057_auto_20191202_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='City Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='State Name'),
        ),
    ]
