# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-16 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0057_auto_20191202_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_superstar',
            field=models.BooleanField(default=False, verbose_name='Is Superstar'),
        ),
    ]
