# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-30 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0059_auto_20200121_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapptimespend',
            name='reference_time',
            field=models.DateTimeField(null=True, verbose_name='reference_time'),
        ),
        migrations.AlterField(
            model_name='videocompleterate',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='videocompleterate',
            name='playtime',
            field=models.PositiveIntegerField(default=0, verbose_name='playtime'),
        ),
        migrations.AlterField(
            model_name='videoplaytime',
            name='playtime',
            field=models.PositiveIntegerField(default=0, verbose_name='playtime'),
        ),
    ]
