# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-24 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0060_userpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_pic',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Cover Pic'),
        ),
    ]
