# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-28 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0061_userprofile_cover_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpay',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
