# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-29 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0062_userpay_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_time_spent',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_vb_playtime',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
