# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-31 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0063_auto_20200129_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='view_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
