# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-01 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0064_auto_20200131_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='own_vb_view_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
