# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-01 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0065_userprofile_own_vb_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='City Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='State Name'),
        ),
    ]
