# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-05 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0062_auto_20200205_1336'),
        ('forum_user', '0066_auto_20200201_2242'),
    ]

    operations = [
    ]
