# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-05 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0060_auto_20200130_1431'),
        ('forum_user', '0067_merge_20200205_1515'),
    ]

    operations = [
    ]
