# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-10 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import forum.core.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0068_merge_20200205_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bolo_score',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='follow_count',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='follower_count',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi')], db_index=True, default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='own_vb_view_count',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=forum.core.utils.models.AutoSlugField(blank=True, populate_from='user.username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_time_spent',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_vb_playtime',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vb_count',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='view_count',
            field=models.BigIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
