# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-18 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0069_auto_20200210_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidlogs',
            name='is_executed',
            field=models.BooleanField(default=False, verbose_name='is_executed'),
        ),
    ]
