# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-18 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0070_androidlogs_is_executed'),
        ('forum_user', '0069_auto_20200213_1807'),
    ]

    operations = [
    ]
