# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-26 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0071_merge_20200218_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='slug'),
        ),
    ]
