# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-18 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0073_auto_20200308_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='for_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
