# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-03 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0076_auto_20200330_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paytm_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile No'),
        ),
    ]
