# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0092_tonguetwister_is_blocked'),
        ('forum_user', '0078_auto_20200413_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoplaytime',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_topic.Topic'),
        ),
    ]
