# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-19 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0079_videoplaytime_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcodeused',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refcode', to='forum_user.ReferralCode'),
        ),
    ]
