# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-30 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0080_auto_20200419_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='android_did',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='android_did'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_guest_user',
            field=models.BooleanField(default=False),
        ),
    ]
