# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-08 01:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0080_auto_20200419_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidlogs',
            name='android_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='android_id'),
        ),
        migrations.AlterField(
            model_name='androidlogs',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='st_logs', to=settings.AUTH_USER_MODEL, verbose_name='profile'),
        ),
    ]
