# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-08 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0074_auto_20200318_0126'),
        ('forum_user', '0081_auto_20200508_0105'),
    ]

    operations = [
    ]
