# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-11 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0082_merge_20200508_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Country Phone Code'),
        ),
    ]
