# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-06 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0082_merge_20200508_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='boost_follow_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Boost Follow'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='boost_like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Boost Like'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='boost_views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Boost View'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='boosted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
