# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-28 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0083_auto_20200606_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='DUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('gender', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], default='', max_length=10, null=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
