# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-30 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0085_userprofile_boost_span'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='boost_follow_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Boost Follow'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='boost_like_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Boost Like'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='boost_span',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Boost Span(Days)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='boost_views_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Boost View'),
        ),
    ]
