# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-01 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0084_userprofile_salary_range'),
        ('forum_user', '0086_auto_20200630_1606'),
    ]

    operations = [
    ]
