# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-01 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0087_merge_20200701_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='boost_span',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Boost Span(Hours)'),
        ),
    ]
