# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-04 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0089_auto_20200701_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Mobile No'),
        ),
    ]
