# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-08 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0090_auto_20200704_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Ref Code'),
        ),
    ]
