# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-16 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_user', '0091_auto_20200708_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightDataDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('for_year', models.PositiveIntegerField(blank=True, choices=[(2019, 2019), (2020, 2020)], null=True, verbose_name='year')),
                ('for_month', models.PositiveIntegerField(blank=True, choices=[(1, b'January'), (2, b'Feburary'), (3, b'Macrh'), (4, b'April'), (5, b'May'), (6, b'June'), (7, b'July'), (8, b'August'), (9, b'September'), (10, b'October'), (11, b'November'), (12, b'December')], null=True, verbose_name='month')),
                ('old_insight_data', models.TextField(blank=True, null=True)),
                ('new_insight_data', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insight_dump', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "InsightDataDump's",
            },
        ),
    ]
