# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-10 01:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0091_auto_20200708_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidlogs',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created_at'),
        ),
    ]
