# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-25 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0092_auto_20200709_1303'),
        ('forum_user', '0092_auto_20200710_0137'),
    ]

    operations = [
    ]
