# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-27 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0093_oldmonthinsightdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_insight_fix',
            field=models.BooleanField(default=False),
        ),
    ]
