# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-24 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0096_monthwisefplaytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_bot_account',
            field=models.BooleanField(default=False),
        ),
    ]
