# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-14 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0098_userprofile_is_event_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_event_creator',
            field=models.BooleanField(default=True),
        ),
    ]
