# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-17 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('advertisement', '0034_auto_20201217_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('view_count', models.PositiveIntegerField(verbose_name='Views')),
                ('install_count', models.PositiveIntegerField(verbose_name='Install')),
                ('ctr', models.FloatField(verbose_name='CTR')),
                ('skip_count', models.PositiveIntegerField(verbose_name='Skips')),
                ('full_watched', models.PositiveIntegerField(verbose_name='Full ad watched')),
                ('average_time_before_install', models.FloatField(verbose_name='Avg. time before Install (Secs)')),
                ('average_time_before_skip', models.FloatField(verbose_name='Avg. time before Skip (Secs)')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='advertisement.Ad')),
            ],
        ),
    ]
