# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-17 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adstats',
            name='average_time_before_install',
        ),
        migrations.RemoveField(
            model_name='adstats',
            name='average_time_before_skip',
        ),
        migrations.RemoveField(
            model_name='adstats',
            name='ctr',
        ),
    ]
