# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-17 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20201217_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adstats',
            name='full_watched',
            field=models.PositiveIntegerField(default=0, verbose_name='Full ad watched'),
        ),
        migrations.AlterField(
            model_name='adstats',
            name='install_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Install'),
        ),
        migrations.AlterField(
            model_name='adstats',
            name='skip_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Skips'),
        ),
        migrations.AlterField(
            model_name='adstats',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Views'),
        ),
    ]
