# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-17 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20201217_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='adstats',
            name='playtime',
            field=models.PositiveIntegerField(default=0, verbose_name='Playtime'),
        ),
    ]
