# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-18 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_adstats_playtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adstats',
            old_name='playtime',
            new_name='install_playtime',
        ),
        migrations.AddField(
            model_name='adstats',
            name='skip_playtime',
            field=models.PositiveIntegerField(default=0, verbose_name='Playtime'),
        ),
    ]
