# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-01-07 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_auto_20210105_1558'),
        ('marketing', '0005_auto_20201218_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Click')),
                ('payment_initiated_count', models.PositiveIntegerField(default=0, verbose_name='Payment Initiated')),
                ('confirm_booking_count', models.PositiveIntegerField(default=0, verbose_name='Confirm Booking')),
                ('total_revenue', models.PositiveIntegerField(default=0, verbose_name='Total Revenue')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='booking.Event')),
            ],
        ),
    ]
