# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0003_topic_reindex_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='language_id',
            field=models.CharField(default='1', max_length=5, verbose_name='language'),
        ),
    ]
