# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0005_auto_20190407_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_media',
            field=models.BooleanField(default=True),
        ),
    ]
