# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0006_topic_is_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='thumbnail',
            field=models.CharField(default='', max_length=150, verbose_name='thumbnail'),
        ),
    ]
