# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0008_auto_20190408_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_category.Category', verbose_name='category'),
        ),
    ]
