# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0010_auto_20190408_2315'),
        ('forum_topic', '0007_topic_thumbnail'),
    ]

    operations = [
    ]
