# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0011_merge_20190408_2341'),
        ('forum_topic', '0011_merge_20190408_2342'),
    ]

    operations = [
    ]
