# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0012_merge_20190409_1345'),
        ('forum_topic', '0012_merge_20190409_1249'),
    ]

    operations = [
    ]
