# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0013_merge_20190409_1814'),
        ('forum_topic', '0013_merge_20190409_1820'),
    ]

    operations = [
    ]
