# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0014_merge_20190409_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='question_audio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='audio title'),
        ),
        migrations.AddField(
            model_name='topic',
            name='question_video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='video title'),
        ),
    ]
