# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0014_merge_20190410_1130'),
        ('forum_topic', '0015_auto_20190410_1317'),
    ]

    operations = [
    ]
