# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0017_auto_20190410_1509'),
        ('forum_topic', '0016_merge_20190410_1435'),
    ]

    operations = [
    ]
