# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0020_auto_20190423_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='share_user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='shared_post',
        ),
    ]
