# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0024_sharetopic_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='media_duration',
            field=models.CharField(default='', max_length=20, verbose_name='duration'),
        ),
    ]
