# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0025_topic_media_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='media_duration',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='duration'),
        ),
    ]
