# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comment', '0013_comment_share_count'),
        ('forum_topic', '0026_auto_20190501_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_topic_comment', to='forum_comment.Comment'),
        ),
        migrations.AddField(
            model_name='sharetopic',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_topic_topic_comment', to='forum_comment.Comment'),
        ),
        migrations.AddField(
            model_name='socialshare',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_share_topic_comment', to='forum_comment.Comment'),
        ),
        migrations.AddField(
            model_name='socialshare',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_share_topic_share', to='forum_topic.Topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='share_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Share count'),
        ),
        migrations.AddField(
            model_name='topic',
            name='total_share_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Share count'),
        ),
        migrations.AlterField(
            model_name='like',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_topic_share', to='forum_topic.Topic'),
        ),
        migrations.AlterField(
            model_name='sharetopic',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_topic_topic_share', to='forum_topic.Topic'),
        ),
    ]
