# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0027_auto_20190501_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-comment_count', '-total_share_count'], 'verbose_name': 'topic', 'verbose_name_plural': 'topics'},
        ),
    ]
