# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0028_auto_20190502_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_like_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharetopic',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_sharetopic_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialshare',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_socialshare_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='st_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
