# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0031_auto_20190507_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='question_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Question image'),
        ),
    ]
