# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0032_topic_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='question_image',
            field=models.TextField(blank=True, null=True, verbose_name='Question image'),
        ),
    ]
