# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0034_auto_20190515_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
