# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0036_auto_20190529_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketmatch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
