# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0037_cricketmatch_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='current_rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Correct Prediction'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='last_rank',
            field=models.PositiveIntegerField(default=0, verbose_name='Correct Prediction'),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
