# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-17 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_topic', '0038_auto_20190603_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='VBseen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='cricketmatch',
            options={'ordering': ['match_datetime']},
        ),
        migrations.AddField(
            model_name='topic',
            name='is_vb',
            field=models.BooleanField(default=False, verbose_name='Is Video Bytes'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_leaderboard_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_like_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_notification_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharetopic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_sharetopic_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialshare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_socialshare_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_topics', to='forum_category.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_voting_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vbseen',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vb_seen', to='forum_topic.Topic'),
        ),
        migrations.AddField(
            model_name='vbseen',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_vbseen_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
