# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0039_auto_20190617_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='last_commented',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Commented'),
        ),
    ]
