# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0041_auto_20190619_0018'),
    ]

    operations = [
        migrations.AddField(model_name='topic', name='backup_url', field=models.TextField(blank=True, verbose_name='backup url'), ),
        migrations.AddField(model_name='topic', name='is_transcoded', field=models.BooleanField(default=False),),
        migrations.AddField(model_name='topic', name='transcode_dump', field=models.TextField(blank=True, verbose_name='Transcode Dump'),),
        migrations.AlterField(model_name='topic', name='last_commented', field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last Commented'),),

        migrations.AddField(
            model_name='topic',
            name='transcode_job_id',
            field=models.TextField(blank=True, verbose_name='Transcode Job ID'),
        ),
        migrations.AddField(
            model_name='topic',
            name='transcode_status_dump',
            field=models.TextField(blank=True, verbose_name='Transcode Status Dump (Job Status)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_transcoded_error',
            field=models.BooleanField(default=False),
        ),
    ]
