# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0041_auto_20190619_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='backup_url',
            field=models.TextField(blank=True, verbose_name='backup url'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_transcoded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='transcode_dump',
            field=models.TextField(blank=True, verbose_name='backup url'),
        ),
    ]
