# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0041_auto_20190619_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='last_commented',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last Commented'),
        ),
    ]
