# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-26 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0042_auto_20190626_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes count'),
        ),
    ]
