# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-03 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0044_tonguetwister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tonguetwister',
            name='descpription',
        ),
        migrations.AddField(
            model_name='tonguetwister',
            name='en_descpription',
            field=models.TextField(blank=True, null=True, verbose_name='English Hash Tag Description'),
        ),
        migrations.AddField(
            model_name='tonguetwister',
            name='hi_descpription',
            field=models.TextField(blank=True, null=True, verbose_name='Hindi Hash Tag Description'),
        ),
        migrations.AddField(
            model_name='tonguetwister',
            name='ta_descpription',
            field=models.TextField(blank=True, null=True, verbose_name='Tamil Hash Tag Description'),
        ),
        migrations.AddField(
            model_name='tonguetwister',
            name='te_descpription',
            field=models.TextField(blank=True, null=True, verbose_name='Telgu Hash Tag Description'),
        ),
    ]
