# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-06 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0045_auto_20190803_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonguetwister',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Picture URL'),
        ),
    ]
