# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_user', '0030_auto_20190808_1740'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('forum_topic', '0047_auto_20190808_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoloActionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Bolo Score')),
                ('action_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='object ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('action', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='forum_user.Weight')),
                ('action_object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='topic type')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='is_monetized',
            field=models.BooleanField(default=True, verbose_name='Is Monetized?'),
        ),
    ]
