# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0048_auto_20190809_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='thumbnail',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='thumbnail'),
        ),
    ]
