# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-14 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0049_auto_20190809_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
