# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0051_auto_20190819_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='facebook_share_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='linkedin_share_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='whatsapp_share_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
