# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0052_auto_20190819_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='twitter_share_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
