# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0053_topic_twitter_share_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialshare',
            name='share_type',
            field=models.CharField(blank=True, choices=[('0', 'facebook'), ('1', 'whatsapp'), ('2', 'linkedin'), ('2', 'twitter')], max_length=10, null=True),
        ),
    ]
