# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0054_auto_20190819_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='vb_height',
            field=models.PositiveIntegerField(default=0, verbose_name='vb height'),
        ),
        migrations.AddField(
            model_name='topic',
            name='vb_width',
            field=models.PositiveIntegerField(default=0, verbose_name='vb width'),
        ),
    ]
