# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-31 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_payment', '0001_initial'),
        ('forum_topic', '0054_auto_20190819_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='boloactionhistory',
            name='encashble_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bolo_score_items', to='forum_payment.EncashableDetail'),
        ),
        migrations.AddField(
            model_name='boloactionhistory',
            name='is_eligible_for_encash',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boloactionhistory',
            name='is_encashed',
            field=models.BooleanField(default=False),
        ),
    ]
