# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-01 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0055_auto_20190915_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='language_id',
            field=models.CharField(blank=True, choices=[('1', 'English'), ('2', 'Hindi'), ('3', 'Tamil'), ('4', 'Telgu')], default='1', max_length=10, null=True),
        ),
    ]
