# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-02 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0055_auto_20190831_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boloactionhistory',
            old_name='encashble_detail',
            new_name='enchashable_detail',
        ),
    ]
