# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-04 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0056_auto_20190902_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boloactionhistory',
            name='enchashable_detail',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bolo_score_items', to='forum_payment.EncashableDetail'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_leaderboard_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_like_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_notification_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharetopic',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_sharetopic_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialshare',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_socialshare_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vbseen',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_vbseen_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voting',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_voting_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
