# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-07 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0057_auto_20190904_1704'),
        ('forum_topic', '0055_auto_20190821_1804'),
    ]

    operations = [
    ]
