# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-23 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0055_auto_20190915_2106'),
        ('forum_topic', '0058_merge_20190907_1316'),
    ]

    operations = [
    ]
