# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-01 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0059_merge_20190923_1317'),
        ('forum_topic', '0056_auto_20191001_1358'),
    ]

    operations = [
    ]
