# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-14 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0060_merge_20191001_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmdevice',
            name='user',
        ),
        migrations.DeleteModel(
            name='FCMDevice',
        ),
    ]
