# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-25 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0062_auto_20191025_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_popular',
            field=models.BooleanField(default=False),
        )
    ]
