# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-25 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0061_auto_20191014_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_monetized',
            field=models.BooleanField(default=False, verbose_name='monetized'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='removed'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='language_id',
            field=models.CharField(blank=True, choices=[('1', 'English'), ('2', 'Hindi'), ('3', 'Tamil'), ('4', 'Telgu')], default='1', max_length=10, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='m2mcategory',
            field=models.ManyToManyField(blank=True, related_name='m2mcategories_topics', to='forum_category.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
    ]
