# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-26 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0062_auto_20191025_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonguetwister',
            name='be_descpription',
            field=models.TextField(blank=True, null=True, verbose_name='Bengali Hash Tag Description'),
        ),
        migrations.AddField(
            model_name='tonguetwister',
            name='ka_descpription',
            field=models.TextField(blank=True, null=True, verbose_name='Kannada Hash Tag Description'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='language_id',
            field=models.CharField(blank=True, choices=[('1', 'English'), ('2', 'Hindi'), ('3', 'Tamil'), ('4', 'Telgu'), ('5', 'Bengali'), ('6', 'Kannada')], default='1', max_length=10, null=True, verbose_name='language'),
        ),
    ]
