# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-19 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0065_auto_20191115_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='hash_tags',
            field=models.ManyToManyField(blank=True, related_name='hash_tag_topics', to='forum_topic.TongueTwister', verbose_name='hash_tags'),
        ),
    ]
