# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-28 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0065_auto_20191115_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_pubsub_popular_push',
            field=models.BooleanField(default=False, verbose_name='Pubsub Push'),
        ),
    ]
