# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-19 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0066_topic_hash_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonguetwister',
            name='hash_counter',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
