# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-02 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0066_topic_is_pubsub_popular_push'),
        ('forum_topic', '0069_auto_20191202_1436'),
    ]

    operations = [
    ]
