# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-02 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0070_merge_20191202_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_pubsub_popular_push',
            field=models.BooleanField(default=False, verbose_name='Popular Push'),
        ),
    ]
