# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-16 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0073_auto_20191211_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonguetwister',
            name='total_views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
