# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-04 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_topic', '0074_tonguetwister_total_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.TextField(verbose_name='video_name')),
                ('time_deleted', models.DateTimeField(auto_now=True)),
                ('plag_text', models.TextField(verbose_name='plag_text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_topics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
