# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-21 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import forum.core.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0074_tonguetwister_total_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title')),
                ('slug', forum.core.utils.models.AutoSlugField(blank=True, db_index=False, populate_from='title')),
                ('tag_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tag line')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Job Description')),
                ('job_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Location')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile')),
                ('document', models.FileField(blank=True, null=True, upload_to='media/documents/')),
                ('jobOpening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_opening', to='forum_topic.JobOpening')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='downloaded_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='downloaded URL'),
        ),
        migrations.AddField(
            model_name='topic',
            name='imp_count',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='moderated'),
        ),
        migrations.AddField(
            model_name='topic',
            name='plag_text',
            field=models.CharField(choices=[('0', 'TikTok'), ('1', 'Helo'), ('2', 'Vigo'), ('3', 'Tik'), ('4', 'Tok'), ('5', 'Vivo'), ('6', 'ShareChat'), ('7', 'Nojoto'), ('8', 'Trell'), ('9', 'ROPOSO'), ('10', 'Likee')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='time_deleted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_pubsub_popular_push',
            field=models.BooleanField(default=False, verbose_name='Popular'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='language_id',
            field=models.CharField(blank=True, choices=[(b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi')], default='1', max_length=10, null=True, verbose_name='language'),
        ),
    ]
