# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-07 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0074_tonguetwister_total_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpenings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Job Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Job Description')),
                ('job_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Location')),
            ],
        ),
    ]
