# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0074_tonguetwister_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='moderated'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_pubsub_popular_push',
            field=models.BooleanField(default=False, verbose_name='Popular'),
        ),
    ]
