# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-07 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0075_jobopenings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobOpenings',
            new_name='JobOpening',
        ),
    ]
