# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-06 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0075_topic_downloaded_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='imp_count',
            field=models.PositiveIntegerField(default=0, verbose_name='views'),
        ),
    ]
