# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-06 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0075_videodeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodeleted',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
