# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0076_topic_imp_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_moderated',
            field=models.BooleanField(default=True, verbose_name='moderated'),
        ),
    ]
