# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-08 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0077_auto_20200107_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='plag_text',
            field=models.CharField(choices=[('0', 'TikTok'), ('1', 'Helo'), ('2', 'Vigo'), ('3', 'Tik'), ('4', 'Tok'), ('5', 'Vivo'), ('6', 'ShareChat'), ('7', 'Nojoto'), ('8', 'Trell'), ('9', 'ROPOSO'), ('10', 'Likee')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='time_deleted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
