# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-07 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0076_auto_20200106_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodeleted',
            name='user',
        ),
        migrations.AddField(
            model_name='topic',
            name='plag_text',
            field=models.CharField(choices=[('0', 'TikTok'), ('1', 'Helo'), ('2', 'VigeoVideo'), ('3', 'MadeWithVivaVideo'), ('4', 'Tik'), ('5', 'Tok'), ('6', 'Vivo'), ('7', 'ShareChat'), ('8', 'Nojoto'), ('9', 'Trell'), ('10', 'ROPOSO'), ('11', 'Like')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='time_deleted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='VideoDeleted',
        ),
    ]
