# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-07 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0077_jobrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='user_doc',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/'),
        ),
    ]
