# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-09 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0077_auto_20200108_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='moderated'),
        ),
    ]
