# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-10 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0075_auto_20200121_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='plag_text',
            field=models.CharField(blank=True, choices=[('0', 'TikTok'), ('1', 'Helo'), ('2', 'Vigo'), ('3', 'Tik'), ('4', 'Tok'), ('5', 'Vivo'), ('6', 'ShareChat'), ('7', 'Nojoto'), ('8', 'Trell'), ('9', 'ROPOSO'), ('10', 'Likee')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='time_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
