# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-24 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0078_auto_20200110_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/', verbose_name='Upload Cover Letter'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='help_text',
            field=models.TextField(blank=True, null=True, verbose_name='Help us know you better'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/documents/', verbose_name='Upload resume'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
