# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-29 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0078_auto_20200110_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='vb_playtime',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
