# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-07 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0079_auto_20200107_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username'),
        ),
    ]
