# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-08 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0080_auto_20200107_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
    ]
