# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-24 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0080_auto_20200124_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry date'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='publish_status',
            field=models.CharField(blank=True, choices=[('0', 'Unpublish'), ('1', 'Publish')], default=1, max_length=10, null=True, verbose_name='Publish'),
        ),
    ]
