# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-08 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import forum.core.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0081_jobopening_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='slug',
            field=forum.core.utils.models.AutoSlugField(blank=True, db_index=False, populate_from='title'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='tag_line',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tag line'),
        ),
    ]
