# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-30 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0079_topic_vb_playtime'),
        ('forum_topic', '0081_auto_20200124_1758'),
    ]

    operations = [
    ]
