# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-08 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0082_auto_20200108_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='jobOpening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_opening', to='forum_topic.JobOpening'),
        ),
    ]
