# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-05 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0082_merge_20200130_0117'),
        ('forum_topic', '0079_auto_20200205_1336'),
    ]

    operations = [
    ]
