# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-09 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0083_auto_20200108_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title'),
        ),
    ]
