# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-11 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0078_topic_is_moderated'),
        ('forum_topic', '0078_auto_20200110_1819'),
        ('forum_topic', '0084_auto_20200109_1114'),
    ]

    operations = [
    ]
