# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-21 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0075_auto_20200107_1139'),
        ('forum_topic', '0084_auto_20200109_1114'),
    ]

    operations = [
    ]
