# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-10 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import forum.core.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0084_auto_20200205_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonguetwister',
            name='hash_counter',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tonguetwister',
            name='hash_tag',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Hash Tag'),
        ),
        migrations.AlterField(
            model_name='tonguetwister',
            name='total_views',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='comment_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='comment count'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='imp_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='views'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='language_id',
            field=models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi')], db_index=True, default='1', max_length=10, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='likes_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Likes count'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='share_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Share count'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=forum.core.utils.models.AutoSlugField(blank=True, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='total_share_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Total Share count'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='vb_playtime',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='views'),
        ),
    ]
