# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-13 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0085_merge_20200111_1428'),
        ('forum_topic', '0078_merge_20200113_1519'),
    ]

    operations = [
    ]
