# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-17 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0085_auto_20200210_1317'),
        ('forum_topic', '0085_topic_has_downloaded_url'),
    ]

    operations = [
    ]
