# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-14 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0085_merge_20200111_1428'),
        ('forum_topic', '0075_auto_20200107_1139'),
        ('forum_topic', '0077_auto_20200107_1236'),
    ]

    operations = [
    ]
