# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-21 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0085_merge_20200121_1232'),
        ('forum_topic', '0086_merge_20200113_1521'),
    ]

    operations = [
    ]
