# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-21 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0086_merge_20200114_1835'),
        ('forum_topic', '0077_auto_20200107_1236'),
    ]

    operations = [
    ]
