# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-21 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0087_auto_20200218_1459'),
        ('forum_topic', '0087_auto_20200218_0134'),
    ]

    operations = [
    ]
