# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-28 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0088_merge_20200221_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='old_backup_url',
            field=models.TextField(blank=True, verbose_name='old_backup url'),
        ),
    ]
