# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-06 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0089_topic_old_backup_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_logo_checked',
            field=models.BooleanField(default=False, verbose_name='Is Logo Checked'),
        ),
    ]
