# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-23 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0091_auto_20200318_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonguetwister',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
