# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-10 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0092_tonguetwister_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='boosted_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='boosted_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='boosted_till',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
    ]
