# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-17 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0092_tonguetwister_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('features', models.CharField(max_length=20)),
                ('weight', models.FloatField(default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='boosted_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='boosted_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='boosted_till',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Boosted Till(Hrs)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 17, 15, 49, 1, 491287)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_like_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Topic Like'),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_share_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Topic Share'),
        ),
        migrations.AddField(
            model_name='topic',
            name='vb_score',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True, verbose_name='VB Score'),
        ),
    ]
