# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-17 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0093_auto_20200417_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_like_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Topic Like'),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_share_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Topic Share'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='vb_score',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True, verbose_name='VB Score'),
        ),
    ]
