# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-19 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0093_auto_20200417_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='boosted_till',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='boost hrs'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_boosted',
            field=models.BooleanField(default=False, verbose_name='boost'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='vb_score',
            field=models.FloatField(blank=True, db_index=True, default=0, null=True, verbose_name='Score'),
        ),
    ]
