# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-27 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0094_auto_20200419_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonguetwister',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tonguetwister',
            name='popular_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Popular Date'),
        ),
    ]
