# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-17 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0094_auto_20200417_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 17, 15, 40, 45, 131254)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
