# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-08 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0096_hashtagviewcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TongueTwisterCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('hash_counter', models.PositiveIntegerField(blank=True, db_index=True, default=1, null=True)),
                ('total_views', models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True)),
                ('language_id', models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi'), (b'10', b'Punjabi'), (b'11', b'Odia')], db_index=True, default='1', max_length=10, null=True, verbose_name='language')),
                ('tongue_twister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tongue_twister_counter', to='forum_topic.TongueTwister')),
            ],
            options={
                'verbose_name': 'TongueTwisterCounter',
                'verbose_name_plural': 'TongueTwisterCounters',
            },
        ),
    ]
