# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-11 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0096_tonguetwistercounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_thumbnail_resized',
            field=models.BooleanField(default=False, verbose_name='Thumbnail Resizd?'),
        ),
    ]
