# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-12 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0097_topic_is_thumbnail_resized'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonguetwister',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
    ]
