# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0040_auto_20200618_1214'),
        ('forum_topic', '0100_topic_safe_backup_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_location', to='drf_spirit.City'),
        ),
    ]
