# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-14 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0100_topic_safe_backup_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='adult_content',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_violent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='logo_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='violent_content',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
