# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-26 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0101_topic_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='downloaded_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='downloaded URL'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='question_audio',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='audio title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='question_video',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='video title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='thumbnail',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='thumbnail'),
        ),
    ]
