# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-17 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0101_auto_20200614_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='profnity_retry',
            field=models.PositiveIntegerField(blank=True, default=2, null=True),
        ),
    ]
