# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-27 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0103_remove_topic_profnity_retry'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='profanity_collage_url',
            field=models.TextField(blank=True, null=True, verbose_name='profanity collage url'),
        ),
    ]
