# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-29 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0102_auto_20200626_2249'),
        ('forum_topic', '0104_topic_profanity_collage_url'),
    ]

    operations = [
    ]
