# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-04 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0106_auto_20200701_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonguetwister',
            name='hash_tag',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Hash Tag'),
        ),
    ]
