# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-08 23:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0107_auto_20200704_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vbseen',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
