# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-16 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0108_auto_20200708_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='FVBseen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view_count')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fvb_seen', to='forum_topic.Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
