# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-17 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0109_fvbseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
