# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-04 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0111_merge_20200728_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingweight',
            name='features',
            field=models.CharField(max_length=200),
        ),
    ]
