# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-19 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0112_auto_20200804_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='popular_boosted',
            field=models.BooleanField(default=False, verbose_name='Popular Boost'),
        ),
        migrations.AddField(
            model_name='topic',
            name='popular_boosted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_boosted',
            field=models.BooleanField(default=False, verbose_name='Super Boost'),
        ),
    ]
