# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-30 22:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_topic', '0113_auto_20200819_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_reported',
            field=models.BooleanField(default=False, verbose_name='reported'),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_moderated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
