# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-31 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0113_auto_20200819_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='FLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='like_count')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='other_share_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='flike',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flike_topic', to='forum_topic.Topic'),
        ),
    ]
