# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-26 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0113_auto_20200819_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='question_audio',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='audio url'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='question_image',
            field=models.TextField(blank=True, null=True, verbose_name='Question url'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='question_video',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='video url'),
        ),
    ]
