# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-31 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0114_auto_20200830_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='report_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Report count'),
        ),
    ]
