# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-09-02 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0114_auto_20200831_2205'),
        ('forum_topic', '0114_auto_20200826_2018'),
    ]

    operations = [
    ]
