# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-09-02 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0115_merge_20200902_0021'),
        ('forum_topic', '0115_topic_report_count'),
    ]

    operations = [
    ]
