# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-09-04 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0116_merge_20200902_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='first_hash_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_hash_tag', to='forum_topic.TongueTwister', verbose_name='first_hash_tag'),
        ),
    ]
