# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-09-08 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0117_topic_first_hash_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonguetwister',
            name='is_popular',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='tonguetwister',
            name='popular_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Popular Date'),
        ),
    ]
