# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-31 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0119_auto_20200916_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_sticky',
            field=models.BooleanField(default=False),
        ),
    ]
