# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-28 15:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0120_topic_is_sticky'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonguetwister',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=['0'], size=None),
        ),
    ]
