# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-04 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0053_auto_20201128_1920'),
        ('forum_topic', '0122_auto_20201128_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_audio_extracted',
            field=models.NullBooleanField(default=False, verbose_name='Is Audio Extracted'),
        ),
        migrations.AddField(
            model_name='topic',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='drf_spirit.MusicAlbum'),
        ),
    ]
