# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0005_category_reindex_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.CharField(blank=True, max_length=150, verbose_name='color'),
        ),
    ]
