# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0006_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='forum_category.Category', verbose_name='category parent'),
        ),
    ]
