# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0007_auto_20190407_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_order',
            field=models.PositiveIntegerField(default=0, verbose_name='category_order'),
        ),
    ]
