# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0008_auto_20190409_1408'),
        ('forum_category', '0008_category_category_order'),
    ]

    operations = [
    ]
