# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-10 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0009_merge_20190410_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_order',
        ),
    ]
