# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0010_remove_category_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_engagement',
            field=models.BooleanField(default=False),
        ),
    ]
