# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0011_category_is_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hindi_title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='hindi_title'),
        ),
        migrations.AddField(
            model_name='category',
            name='tamil_title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='tamil_title'),
        ),
        migrations.AddField(
            model_name='category',
            name='telgu_title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='telgu_title'),
        ),
    ]
