# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-26 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0012_auto_20190503_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bengali_title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='bengali_title'),
        ),
        migrations.AddField(
            model_name='category',
            name='kannada_title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='kannada_title'),
        ),
    ]
