# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-11 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0013_auto_20191026_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
