# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-02 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0014_category_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gujrati_title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='gujrati_title'),
        ),
        migrations.AddField(
            model_name='category',
            name='malayalam_title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='malayalam_title'),
        ),
        migrations.AddField(
            model_name='category',
            name='marathi_title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='marathi_title'),
        ),
    ]
