# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-23 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0015_auto_20191202_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dark_category_image',
            field=models.CharField(blank=True, max_length=150, verbose_name='Dark Category Image URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.CharField(blank=True, max_length=150, verbose_name='Category Image URL'),
        ),
    ]
