# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-28 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0016_auto_20200123_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryViewCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[(b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi')], max_length=10, null=True, verbose_name='language')),
                ('view_count', models.BigIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_counter', to='forum_category.Category', verbose_name='category')),
            ],
        ),
    ]
