# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-05 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0018_auto_20200128_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryviewcounter',
            name='language',
            field=models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi')], max_length=10, null=True, verbose_name='language'),
        ),
    ]
