# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-08 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0019_auto_20200205_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='odia_title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='odia_title'),
        ),
        migrations.AddField(
            model_name='category',
            name='punjabi_title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='punjabi_title'),
        ),
        migrations.AlterField(
            model_name='categoryviewcounter',
            name='language',
            field=models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi'), (b'10', b'Punjabi'), (b'11', b'Odia')], max_length=10, null=True, verbose_name='language'),
        ),
    ]
