# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-01 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0020_auto_20200308_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bhojpuri_title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='bhojpuri_title'),
        ),
        migrations.AddField(
            model_name='category',
            name='haryanvi_title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='haryanvi_title'),
        ),
        migrations.AlterField(
            model_name='categoryviewcounter',
            name='language',
            field=models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi'), (b'10', b'Punjabi'), (b'11', b'Odia'), (b'12', b'Bhojpuri'), (b'13', b'Haryanvi')], max_length=10, null=True, verbose_name='language'),
        ),
    ]
