# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-12 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUploadTranscode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_file_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='S3 File URL')),
                ('transcoded_file_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Transcoded File URL')),
                ('transcode_job_id', models.TextField(blank=True, verbose_name='Transcode Job ID')),
                ('filename_uploaded', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Filename Uploaded')),
                ('filename_changed', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Filename changed')),
                ('folder_to_upload', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Filename changed')),
                ('folder_to_upload_changed', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Filename changed')),
            ],
        ),
    ]
