# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-12 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videouploadtranscode',
            name='transcode_dump',
            field=models.TextField(blank=True, verbose_name='Transcode Dump'),
        ),
    ]
