# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-03 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0002_videouploadtranscode_transcode_dump'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category Name')),
            ],
        ),
        migrations.AddField(
            model_name='videouploadtranscode',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jarvis.VideoCategory'),
        ),
    ]
