# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-09 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0004_auto_20191004_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='videouploadtranscode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
