# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-10 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0005_videouploadtranscode_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='videouploadtranscode',
            name='meta_descp',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='videouploadtranscode',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='videouploadtranscode',
            name='meta_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='videouploadtranscode',
            name='slug',
            field=models.SlugField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videouploadtranscode',
            name='thumnbnail_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Thumbnail URL'),
        ),
    ]
