# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-10 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0006_auto_20191010_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videouploadtranscode',
            name='meta_descp',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
    ]
