# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-10 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0007_auto_20191010_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videouploadtranscode',
            old_name='thumnbnail_url',
            new_name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='videouploadtranscode',
            name='media_duration',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='duration'),
        ),
    ]
