# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-14 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0009_fcmdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='device_type',
            field=models.CharField(blank=True, choices=[('1', 'Android'), ('2', 'iOS'), ('3', 'Web')], default='0', max_length=10, null=True),
        ),
    ]
