# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-16 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0011_pushnotification_pushnotificationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='scheduled_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
