# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-17 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0012_auto_20191016_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='instance_id',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='instance_id'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='notification_type',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='notification_type'),
        ),
    ]
