# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-19 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0014_auto_20191019_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='user_group',
            field=models.CharField(blank=True, choices=[('0', 'All'), ('1', 'Installed but did not sign up till 3 hours'), ('2', 'Installed and never signed up'), ('3', 'Signed up but never played a video'), ('4', 'Signed up but no opening of app since 24 hours'), ('5', 'Signed up but no opening of app since 72 hours '), ('6', 'Never created a video')], default='0', max_length=10, null=True),
        ),
    ]
