# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-20 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0015_auto_20191019_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('0', 'video page'), ('1', 'user'), ('2', 'category'), ('3', 'hashtag'), ('4', 'Announcements')], default='4', max_length=10, null=True),
        ),
    ]
