# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-21 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0016_auto_20191020_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='is_executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='repeated_hour',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
