# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-22 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0017_auto_20191021_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='instance_id',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='instance_id'),
        ),
    ]
