# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-26 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0018_auto_20191022_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='language',
            field=models.CharField(blank=True, choices=[('0', 'All'), ('1', 'English'), ('2', 'Hindi'), ('3', 'Tamil'), ('4', 'Telgu'), ('5', 'Bengali'), ('4', 'Kannada')], default='0', max_length=10, null=True),
        ),
    ]
