# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-30 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0067_auto_20191130_1807'),
        ('jarvis', '0020_auto_20191111_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateDistrictLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('state_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='State Name')),
                ('district_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='District Name')),
                ('state_language', models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'4', b'Kannada')], default='1', max_length=10, null=True)),
                ('district_language', models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'4', b'Kannada')], default='1', max_length=10, null=True)),
                ('response_dump', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'State District Language',
                'verbose_name_plural': 'State District Languages',
            },
        ),
        migrations.AddField(
            model_name='videouploadtranscode',
            name='is_topic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videouploadtranscode',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum_topic.Topic'),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='language',
            field=models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'4', b'Kannada')], default='0', max_length=10, null=True),
        ),
    ]
