# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-03 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jarvis', '0023_auto_20191202_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='videouploadtranscode',
            name='uploaded_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jarvis_videouploadtranscode_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
