# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-04 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0024_videouploadtranscode_uploaded_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='title'),
        ),
    ]
