# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-09 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0026_fcmdevice_is_uninstalled'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='uninstalled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
