# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-09 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0027_fcmdevice_uninstalled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='uninstalled_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
