# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-09 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0015_auto_20191202_1458'),
        ('jarvis', '0029_dashboardmetrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardmetrics',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_notification', to='forum_category.Category', verbose_name='category'),
        ),
    ]
