# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-11 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0029_dashboardmetrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardmetrics',
            options={'ordering': ['date']},
        ),
    ]
