# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-21 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0030_auto_20200111_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmetrics',
            name='metrics',
            field=models.CharField(blank=True, choices=[('0', 'Video Created'), ('1', 'Video Views'), ('2', 'Bolo Actions'), ('3', 'Video Shares'), ('4', 'Video Creators'), ('5', 'Number of Installs'), ('6', 'Monthly Active Users'), ('7', 'Unique Video Views')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmetrics',
            name='metrics_slab',
            field=models.CharField(blank=True, choices=[('0', '5 to 24'), ('1', '25 to 59'), ('2', '60 or more'), ('3', 'Likes'), ('4', 'Comments'), ('5', 'Shares'), ('6', 'Organic'), ('7', 'Paid'), ('t', 'Total')], default=None, max_length=10, null=True),
        ),
    ]
