# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-17 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0030_auto_20200109_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='image_url'),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='user_group',
            field=models.CharField(blank=True, choices=[('0', 'All'), ('1', 'Installed but did not sign up till 3 hours'), ('2', 'Installed and never signed up'), ('3', 'Signed up but never played a video'), ('4', 'Signed up but no opening of app since 24 hours'), ('5', 'Signed up but no opening of app since 72 hours '), ('6', 'Never created a video'), ('7', 'Test User'), ('8', 'Particular User')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pushnotificationuser',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Not Opened'), ('1', 'Opened'), ('2', 'Sent')], default='0', max_length=10, null=True),
        ),
    ]
