# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-27 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0030_auto_20200111_1429'),
        ('jarvis', '0031_auto_20200117_1442'),
    ]

    operations = [
    ]
