# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-29 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('jarvis', '0032_merge_20200127_1427'),
        ('jarvis', '0032_auto_20200121_1303'),
    ]

    operations = [
    ]
