# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-05 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0033_merge_20200129_1727'),
        ('jarvis', '0034_auto_20200205_1336'),
    ]

    operations = [
    ]
