# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-07 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0037_pushnotification_particular_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='user_group',
            field=models.CharField(blank=True, choices=[('0', 'All'), ('1', 'Installed but did not sign up till 3 hours'), ('2', 'Installed and never signed up'), ('3', 'Signed up but never played a video'), ('4', 'Signed up but no opening of app since 24 hours'), ('5', 'Signed up but no opening of app since 72 hours '), ('6', 'Never created a video'), ('7', 'Test User'), ('8', 'Particular User'), ('9', 'Creators'), ('10', 'Active Users')], default='0', max_length=10, null=True),
        ),
    ]
