# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-07 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0038_auto_20200207_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='days_ago',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
