# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-11 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0039_pushnotification_days_ago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotificationuser',
            name='device',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_notification_device', to=settings.FCM_DEVICE_MODEL),
        ),
    ]
