# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-19 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0041_auto_20200218_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fcmdevice',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushnotificationuser',
            name='response_dump',
            field=models.TextField(blank=True, null=True),
        ),
    ]
