# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-19 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0042_auto_20200219_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='current_activity',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
