# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-20 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0043_auto_20200219_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmetricsjarvis',
            name='metrics_language_options',
            field=models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmetrics',
            name='metrics',
            field=models.CharField(blank=True, choices=[('0', 'Video Created'), ('1', 'Video Views'), ('2', 'Bolo Actions'), ('3', 'Video Shares'), ('4', 'New Video Creators'), ('5', 'Number of Installs'), ('6', 'DAU'), ('7', 'Unique Video Views'), ('8', 'MAU'), ('9', 'Total Video Creators')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmetricsjarvis',
            name='metrics',
            field=models.CharField(blank=True, choices=[('0', 'Video Created'), ('1', 'Video Views'), ('2', 'Bolo Actions'), ('3', 'Video Shares'), ('4', 'New Video Creators'), ('5', 'Number of Installs'), ('6', 'DAU'), ('7', 'Unique Video Views'), ('8', 'MAU'), ('9', 'Total Video Creators')], default='0', max_length=10, null=True),
        ),
    ]
