# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-26 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0042_auto_20200218_1449'),
        ('jarvis', '0044_auto_20200219_1806'),
    ]

    operations = [
    ]
