# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-27 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0046_auto_20200226_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('0', 'video page'), ('1', 'user'), ('2', 'category'), ('3', 'hashtag'), ('4', 'Announcements'), ('5', 'Create Video Byte')], default='4', max_length=10, null=True),
        ),
    ]
