# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-24 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0048_auto_20200224_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmetricsjarvis',
            name='category_slab_options',
            field=models.CharField(blank=True, choices=[(0, b'Health'), (1, b'Fitness'), (2, b'Career and Jobs'), (3, b'General Knowledge'), (4, b'Motivation'), (5, b'Finance Knowledge'), (6, b'Fashion and Beauty'), (7, b'Lifestyle and Travel'), (8, b'Food and Cooking'), (9, b'Technology'), (10, b'Entertainment'), (11, b'Shopping / Reviews'), (12, b'Relationships'), (13, b'English Learning'), (14, b'Entrance Exams'), (15, b'Sports'), (16, b'Open Podcasts'), (17, b'Parent')], default='0', max_length=10, null=True),
        ),
    ]
