# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-24 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0049_dashboardmetricsjarvis_category_slab_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmetricsjarvis',
            name='category_slab_options',
            field=models.CharField(blank=True, choices=[(67, b'Health'), (68, b'Fitness'), (62, b'Career and Jobs'), (63, b'General Knowledge'), (65, b'Motivation'), (75, b'Finance Knowledge'), (70, b'Fashion and Beauty'), (71, b'Lifestyle and Travel'), (69, b'Food and Cooking'), (72, b'Technology'), (74, b'Entertainment'), (73, b'Shopping / Reviews'), (66, b'Relationships'), (76, b'English Learning'), (64, b'Entrance Exams'), (60, b'Sports'), (61, b'Open Podcasts'), (58, b'Parent')], default='0', max_length=10, null=True),
        ),
    ]
