# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-27 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0055_auto_20200226_1737'),
        ('jarvis', '0044_auto_20200219_1806'),
    ]

    operations = [
    ]
