# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-28 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0060_auto_20200228_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardmetricsjarvis',
            name='category_slab_options',
        ),
    ]
