# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-11 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0033_merge_20200129_1727'),
        ('jarvis', '0062_auto_20200308_2003'),
    ]

    operations = [
    ]
