# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-11 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0020_auto_20200308_2003'),
        ('jarvis', '0063_merge_20200311_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_notification', to='forum_category.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='image_url'),
        ),
        migrations.AlterField(
            model_name='pushnotificationuser',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Not Opened'), ('1', 'Opened'), ('2', 'Sent')], default='0', max_length=10, null=True),
        ),
    ]
