# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-14 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0064_banneruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banneruser',
            name='hash_tag',
        ),
        migrations.AddField(
            model_name='banneruser',
            name='term',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='term'),
        ),
    ]
