# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-15 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0065_auto_20200414_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banneruser',
            options={'verbose_name': 'Banner User', 'verbose_name_plural': 'Banner Users'},
        ),
    ]
