# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-21 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_category', '0020_auto_20200308_2003'),
        ('jarvis', '0066_auto_20200415_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCountNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi'), (b'10', b'Punjabi'), (b'11', b'Odia')], default='0', max_length=10, null=True)),
                ('user_group', models.CharField(blank=True, choices=[('0', 'All'), ('1', 'Installed but did not sign up till 3 hours'), ('2', 'Installed and never signed up'), ('3', 'Signed up but never played a video'), ('4', 'Signed up but no opening of app since 24 hours'), ('5', 'Signed up but no opening of app since 72 hours '), ('6', 'Never created a video'), ('7', 'Test User'), ('8', 'Particular User'), ('9', 'Creators'), ('10', 'Active Users')], default='0', max_length=10, null=True)),
                ('no_of_user', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fcm_users', models.TextField(null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_count_notification_category', to='forum_category.Category', verbose_name='category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='m2mcategory',
            field=models.ManyToManyField(blank=True, related_name='m2mcategories_notification', to='forum_category.Category', verbose_name='category'),
        ),
    ]
