# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-28 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0067_auto_20200421_2032'),
        ('jarvis', '0064_auto_20200311_1126'),
    ]

    operations = [
    ]
