# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-08 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0067_auto_20200421_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercountnotification',
            options={'verbose_name': 'UserCountNotification', 'verbose_name_plural': 'UserCountNotifications'},
        ),
    ]
