# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-15 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0068_merge_20200428_1633'),
        ('jarvis', '0069_report'),
    ]

    operations = [
    ]
