# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-01 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0071_remove_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmetricsjarvis',
            name='metrics_language_options',
            field=models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi'), (b'10', b'Punjabi'), (b'11', b'Odia'), (b'12', b'Bhojpuri'), (b'13', b'Haryanvi')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='language',
            field=models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi'), (b'10', b'Punjabi'), (b'11', b'Odia'), (b'12', b'Bhojpuri'), (b'13', b'Haryanvi')], default='0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='statedistrictlanguage',
            name='district_language',
            field=models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi'), (b'10', b'Punjabi'), (b'11', b'Odia'), (b'12', b'Bhojpuri'), (b'13', b'Haryanvi')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='statedistrictlanguage',
            name='state_language',
            field=models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi'), (b'10', b'Punjabi'), (b'11', b'Odia'), (b'12', b'Bhojpuri'), (b'13', b'Haryanvi')], default='1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usercountnotification',
            name='language',
            field=models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi'), (b'10', b'Punjabi'), (b'11', b'Odia'), (b'12', b'Bhojpuri'), (b'13', b'Haryanvi')], default='0', max_length=10, null=True),
        ),
    ]
