# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-10 18:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0073_auto_20200707_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmdevice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
