# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-29 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0074_auto_20200709_1303'),
        ('jarvis', '0074_auto_20200710_1834'),
    ]

    operations = [
    ]
