# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comment', '0004_auto_20160315_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='language_id',
            field=models.CharField(default='1', max_length=5, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='comment',
            name='media_duration',
            field=models.CharField(default='', max_length=20, verbose_name='duration'),
        ),
    ]
