# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comment', '0004_auto_20160315_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
