# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comment', '0006_comment_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_comment', to='forum_topic.Topic'),
        ),
    ]
