# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comment', '0007_auto_20190407_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_audio',
            field=models.BooleanField(default=False),
        ),
    ]
