# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comment', '0008_comment_is_audio'),
        ('forum_comment', '0005_comment_is_video'),
    ]

    operations = [
    ]
