# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comment', '0010_remove_comment_is_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-likes_count'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
