# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comment', '0011_auto_20190428_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='media_duration',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='duration'),
        ),
    ]
