# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comment', '0012_auto_20190501_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='share_count',
            field=models.PositiveIntegerField(default=0, verbose_name='share count'),
        ),
    ]
