# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comment', '0013_comment_share_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
