# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comment', '0016_auto_20190515_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-media_duration'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
