# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-11 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comment', '0021_auto_20191202_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(verbose_name='comment')),
                ('comment_html', models.TextField(verbose_name='comment html')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_history', to='forum_comment.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
