# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-11 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_topic', '0073_auto_20191211_1512'),
        ('forum_comment', '0022_commenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hash_tags',
            field=models.ManyToManyField(blank=True, related_name='hash_tag_comment', to='forum_topic.TongueTwister', verbose_name='hash_tags'),
        ),
        migrations.AddField(
            model_name='commenthistory',
            name='hash_tags',
            field=models.ManyToManyField(blank=True, related_name='hash_tag_comment_history', to='forum_topic.TongueTwister', verbose_name='hash_tags'),
        ),
    ]
