# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-09-21 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comment', '0028_auto_20200709_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gify_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
