# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-08 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comment', '0029_comment_gify_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiphyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('giphy_id', models.TextField(verbose_name='giphy_id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
