# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-08 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_comment', '0030_giphydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giphydetails',
            name='giphy_id',
            field=models.TextField(unique=True, verbose_name='giphy_id'),
        ),
    ]
