# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-23 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_userkyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Account Holder Name'),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='paytm_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paytm Mobile No'),
        ),
        migrations.AddField(
            model_name='userkyc',
            name='is_kyc_bank_details_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userkyc',
            name='kyc_bank_details_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userkyc',
            name='mode_of_transaction',
            field=models.CharField(blank=True, choices=[('1', 'Bank Account'), ('2', 'Paytm Wallet')], default='1', max_length=10, null=True),
        ),
    ]
