# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-26 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_userkyc', '0002_auto_20190823_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycbasicinfo',
            old_name='lastname_name',
            new_name='last_name',
        ),
    ]
