# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-04 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_userkyc', '0003_auto_20190826_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_userkyc_additionalinfo_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_userkyc_bankdetail_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kycbasicinfo',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_userkyc_kycbasicinfo_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_userkyc_kycdocument_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_userkyc_userkyc_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
