# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-10 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_userkyc', '0004_auto_20190904_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[('1', 'Information Incomplete'), ('2', 'Information not matched'), ('99', 'Others')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='reject_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Reject Text'),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[('1', 'Information Incomplete'), ('2', 'Information not matched'), ('99', 'Others')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='reject_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Reject Text'),
        ),
        migrations.AddField(
            model_name='kycbasicinfo',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycbasicinfo',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[('1', 'Information Incomplete'), ('2', 'Mobile not Verified'), ('3', 'Email not Verified'), ('4', 'Pic not clear'), ('99', 'Others')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kycbasicinfo',
            name='reject_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Reject Text'),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[('1', 'Information Incomplete'), ('2', 'Information not matched'), ('3', 'Pic not clear'), ('99', 'Others')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='reject_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Reject Text'),
        ),
    ]
