from __future__ import unicode_literals
from django.conf.urls import url, include
from jarvis import views
urlpatterns = [
    url(r'^$',views.home,name='jarvis-home'),
    url(r'^importcsv/$',views.importcsv,name = 'import-csv'),
    url(r'^getcsvdata/$',views.getcsvdata),
    url(r'^csvupload/$',views.uploaddata),
    url(r'^geturl/$',views.geturl),
    url(r'^get_kyc_user_list/$',views.get_kyc_user_list,name='get_kyc_user_list'),
    url(r'^single_kyc/$',views.get_kyc_of_user,name='get_kyc_of_user'),
    url(r'^get_secret_file/$',views.SecretFileView, name='SecretFileView'),
    url(r'^get_encashable_detail/$',views.get_encashable_detail, name='get_encashable_detail'),
    url(r'^get_single_encash_detail/$',views.get_single_encash_detail, name='get_single_encash_detail'),
    url(r'^calculate_encashable_detail/$',views.calculate_encashable_detail, name='calculate_encashable_detail'),
    url(r'^bolo_payment/$',views.PaymentView.as_view(),name='bolo_payment'),
    url(r'^bolo_cycle/$',views.PaymentCycleView.as_view(),name='bolo_cycle'),
    url(r'^accept_kyc/$',views.accept_kyc, name='accept_kyc'),
    url(r'^reject_kyc/$',views.reject_kyc, name='reject_kyc'),
    url(r'^uploadvideofile/$',views.uploadvideofile,name = 'uploadvideofile'),
    url(r'^upload_n_transcode/$',views.upload_n_transcode),
    url(r'^upload_details/$',views.upload_details),
    url(r'^uploaded_list/$',views.uploaded_list),
    url(r'^user_statistics/$', views.user_statistics),
    url(r'^video_statistics/$', views.video_statistics),
    url(r'^get_user_stats/$', views.get_stats_data),
    url(r'^get_hau_data/$', views.get_hau_data),
    url(r'^get_dau_data/$', views.get_dau_data),
    url(r'^get_installs_data/$', views.get_installs_data),
    url(r'^get_impr_data/$', views.get_daily_impressions_data),
    url(r'^get_top_impr/$', views.get_top_impressions_data),
    url(r'^get_weekly_vplay_data/$', views.weekly_vplay_data),
    url(r'^get_daily_vplay_data/$', views.daily_vplay_data),
    #url(r'^barchart/$', views.barchart, name= 'create_barchart'),              # url for rendering the bar chart
]