# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingUpOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=75, verbose_name='title')),
                ('otp', models.CharField(editable=False, max_length=10, verbose_name='OTP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('used_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Used At')),
            ],
        ),
    ]
