# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-19 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0002_auto_20190419_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='singupotp',
            name='is_for_change_phone',
            field=models.BooleanField(default=False, verbose_name='is for change phone number?'),
        ),
    ]
