# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-08 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0004_userjarvisdump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjarvisdump',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
