# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0005_auto_20190808_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjarvisdump',
            name='is_executed',
            field=models.BooleanField(default=False, verbose_name='Is Executed'),
        ),
    ]
