# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0005_auto_20190808_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_log_statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250, null=True, verbose_name='user')),
                ('user_phone_details', models.CharField(blank=True, max_length=250, null=True, verbose_name='phone_details')),
                ('user_lang', models.CharField(blank=True, max_length=250, null=True, verbose_name='user_lang')),
                ('num_profile_follow', models.TextField(blank=True, null=True, verbose_name='num_profile_follow')),
                ('num_profile_unfollow', models.TextField(blank=True, null=True, verbose_name='num_profile_unfollow')),
                ('num_viewed_profiles', models.TextField(blank=True, null=True, verbose_name='num_viewed_profiles')),
                ('num_profile_reported', models.TextField(blank=True, null=True, verbose_name='num_profile_reported')),
                ('num_viewed_following_list', models.TextField(blank=True, null=True, verbose_name='num_viewed_following_list')),
                ('num_entry_points', models.TextField(blank=True, null=True, verbose_name='num_entry_points')),
                ('num_vb_commented', models.TextField(blank=True, null=True, verbose_name='num_vb_commented')),
                ('num_vb_liked', models.TextField(blank=True, null=True, verbose_name='num_vb_liked')),
                ('num_vb_shared', models.TextField(blank=True, null=True, verbose_name='num_vb_shared')),
                ('num_vb_unliked', models.TextField(blank=True, null=True, verbose_name='num_vb_unliked')),
                ('num_vb_viewed', models.TextField(blank=True, null=True, verbose_name='num_vb_viewed')),
            ],
        ),
    ]
