# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0006_user_log_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_entry_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250, null=True, verbose_name='user')),
                ('entrypoint', models.CharField(max_length=400, verbose_name='entrypoint')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='user_follow_unfollow_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250, null=True, verbose_name='user')),
                ('follower_id', models.TextField(blank=True, null=True, verbose_name='follower_id')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('relationship_type', models.CharField(choices=[(b'1', b'follow'), (b'2', b'unfollow')], max_length=50, verbose_name='relationship_type')),
            ],
        ),
        migrations.CreateModel(
            name='user_videotype_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250, null=True, verbose_name='user')),
                ('videoid', models.CharField(blank=True, max_length=250, null=True, verbose_name='videoid')),
                ('timestamp', models.DateTimeField(blank=True, verbose_name='timestamp')),
                ('video_type', models.CharField(choices=[(b'1', b'commented'), (b'2', b'shared'), (b'3', b'liked'), (b'4', b'unliked'), (b'5', b'viewed')], max_length=50, verbose_name='video_type')),
            ],
        ),
        migrations.CreateModel(
            name='video_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoid', models.CharField(max_length=250, verbose_name='videoid')),
                ('timestamp', models.DateTimeField(null=True, verbose_name='timestamp')),
            ],
        ),
        migrations.AddField(
            model_name='user_log_statistics',
            name='session_starttime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='session_starttime'),
        ),
    ]
