# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-22 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0007_auto_20190820_1454'),
        ('drf_spirit', '0006_userjarvisdump_is_executed'),
    ]

    operations = [
    ]
