# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-09 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0008_merge_20190822_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250, null=True, verbose_name='user')),
                ('categoryid', models.CharField(max_length=250, null=True, verbose_name='categoryid')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('category_status', models.CharField(choices=[(b'1', b'added'), (b'2', b'removed')], max_length=250, verbose_name='category_status')),
            ],
        ),
        migrations.CreateModel(
            name='user_viewed_followers_following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250, null=True, verbose_name='user')),
                ('profileid', models.CharField(max_length=250, verbose_name='profileid')),
                ('timestamp', models.CharField(blank=True, max_length=250, verbose_name='timestamp')),
                ('relationship_type', models.CharField(choices=[(b'1', b'following'), (b'2', b'followers')], max_length=250, verbose_name='relationship_type')),
            ],
        ),
        migrations.CreateModel(
            name='video_shared_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250, null=True, verbose_name='user')),
                ('videoid', models.CharField(max_length=250, null=True, verbose_name='videoid')),
                ('share_platform', models.CharField(blank=True, max_length=400, null=True, verbose_name='share_platform')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_follow_unfollow_details',
            name='follower_id',
        ),
        migrations.AddField(
            model_name='user_follow_unfollow_details',
            name='profileid',
            field=models.TextField(blank=True, null=True, verbose_name='profileid'),
        ),
        migrations.AlterField(
            model_name='user_follow_unfollow_details',
            name='relationship_type',
            field=models.CharField(choices=[(b'1', b'follow'), (b'2', b'unfollow'), (b'3', b'report'), (b'4', b'shared')], max_length=50, verbose_name='relationship_type'),
        ),
        migrations.AlterField(
            model_name='user_videotype_details',
            name='video_type',
            field=models.CharField(choices=[(b'1', b'commented'), (b'2', b'shared'), (b'3', b'liked'), (b'4', b'unliked'), (b'5', b'viewed')], max_length=250, verbose_name='video_type'),
        ),
        migrations.AlterField(
            model_name='userjarvisdump',
            name='dump',
            field=models.TextField(blank=True, null=True, verbose_name='dump'),
        ),
        migrations.AlterField(
            model_name='userjarvisdump',
            name='dump_type',
            field=models.CharField(choices=[(b'1', b'user_activities_data'), (b'2', b'error_logs')], max_length=50, verbose_name='dump_type'),
        ),
        migrations.AlterField(
            model_name='userjarvisdump',
            name='is_executed',
            field=models.BooleanField(default=False, verbose_name='is_executed'),
        ),
        migrations.AlterField(
            model_name='userjarvisdump',
            name='sync_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='sync_time'),
        ),
    ]
