# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-11 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0009_auto_20190909_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_entry_point',
            name='user',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='user_follow_unfollow_details',
            name='profileid',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='profileid'),
        ),
        migrations.AlterField(
            model_name='user_follow_unfollow_details',
            name='user',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='user_interest',
            name='categoryid',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='categoryid'),
        ),
        migrations.AlterField(
            model_name='user_interest',
            name='user',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='user_log_statistics',
            name='user',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='user_videotype_details',
            name='user',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='user_videotype_details',
            name='videoid',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='videoid'),
        ),
        migrations.AlterField(
            model_name='user_viewed_followers_following',
            name='profileid',
            field=models.CharField(db_index=True, max_length=250, verbose_name='profileid'),
        ),
        migrations.AlterField(
            model_name='user_viewed_followers_following',
            name='user',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='userjarvisdump',
            name='dump_type',
            field=models.CharField(choices=[(b'1', b'user_activities_data'), (b'2', b'error_logs'), (b'3', b'hardware_info')], max_length=50, verbose_name='dump_type'),
        ),
        migrations.AlterField(
            model_name='video_details',
            name='videoid',
            field=models.CharField(db_index=True, max_length=250, verbose_name='videoid'),
        ),
        migrations.AlterField(
            model_name='video_shared_details',
            name='user',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='video_shared_details',
            name='videoid',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='videoid'),
        ),
    ]
