# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-20 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0010_auto_20190911_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=250, null=True, verbose_name='user')),
                ('searchquery', models.CharField(max_length=1000, null=True, verbose_name='searchquery')),
                ('timestamp', models.DateTimeField(null=True, verbose_name='timestamp')),
            ],
        ),
    ]
