# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-21 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0011_user_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity_time_spend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=250, null=True, verbose_name='userid')),
                ('fragmentid', models.CharField(db_index=True, max_length=250, null=True, verbose_name='fragmentid')),
                ('starttime', models.DateTimeField(null=True, verbose_name='starttime')),
                ('pausetime', models.DateTimeField(null=True, verbose_name='pausetime')),
                ('difference', models.PositiveIntegerField(default=0, editable=False, verbose_name='time_difference')),
            ],
        ),
    ]
