# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-21 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0012_activity_time_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_time_spend',
            name='fragmentid',
            field=models.CharField(db_index=True, max_length=550, null=True, verbose_name='fragmentid'),
        ),
    ]
