# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-23 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0013_auto_20190921_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_videotype_details',
            name='user',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='user'),
        ),
    ]
