# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-23 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0016_auto_20190923_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='activity_time_spend',
            new_name='ActivityTimeSpend',
        ),
        migrations.RenameModel(
            old_name='user_entry_point',
            new_name='UserEntryPoint',
        ),
        migrations.RenameModel(
            old_name='user_follow_unfollow_details',
            new_name='UserFollowUnfollowDetails',
        ),
        migrations.RenameModel(
            old_name='user_interest',
            new_name='UserInterest',
        ),
        migrations.RenameModel(
            old_name='user_search',
            new_name='UserSearch',
        ),
        migrations.RenameModel(
            old_name='user_videotype_details',
            new_name='UserVideoTypeDetails',
        ),
        migrations.RenameModel(
            old_name='user_viewed_followers_following',
            new_name='UserViewedFollowersFollowing',
        ),
        migrations.RenameModel(
            old_name='video_details',
            new_name='VideoDetails',
        ),
        migrations.RenameModel(
            old_name='video_shared_details',
            new_name='VideoSharedDetails',
        ),
    ]
