# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-04 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0018_dailyactiveuser_hourlyactiveuser_monthlyactiveuser_usertimerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyactiveuser',
            name='year',
            field=models.PositiveIntegerField(default=2019, editable=False, verbose_name='year'),
        ),
    ]
