# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-04 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0019_monthlyactiveuser_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlyactiveuser',
            name='hour_week',
        ),
        migrations.AddField(
            model_name='hourlyactiveuser',
            name='hour',
            field=models.CharField(max_length=250, null=True, verbose_name='hour'),
        ),
        migrations.AddField(
            model_name='hourlyactiveuser',
            name='month',
            field=models.CharField(max_length=250, null=True, verbose_name='month'),
        ),
        migrations.AddField(
            model_name='hourlyactiveuser',
            name='year',
            field=models.PositiveIntegerField(default=2019, editable=False, verbose_name='year'),
        ),
    ]
