# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-04 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0020_auto_20191004_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlyactiveuser',
            name='day_week',
        ),
        migrations.AddField(
            model_name='hourlyactiveuser',
            name='day_month',
            field=models.CharField(max_length=250, null=True, verbose_name='day_month'),
        ),
    ]
