# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-04 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0021_auto_20191004_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyactiveuser',
            name='day_week',
            field=models.CharField(max_length=250, null=True, verbose_name='day_week'),
        ),
    ]
