# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0024_dailyactiveuser_date_time_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_memory', models.PositiveIntegerField(default=0.0, editable=False, verbose_name='total_memory')),
                ('memory_free', models.PositiveIntegerField(default=0, editable=False, verbose_name='memory_free')),
                ('memory_available', models.PositiveIntegerField(default=0, editable=False, verbose_name='memory_available')),
                ('swap_cached', models.PositiveIntegerField(default=0, editable=False, verbose_name='swap_cached')),
                ('active', models.PositiveIntegerField(default=0, editable=False, verbose_name='active')),
                ('inactive', models.PositiveIntegerField(default=0, editable=False, verbose_name='inactive')),
                ('unevictable', models.PositiveIntegerField(default=0, editable=False, verbose_name='unevictable')),
                ('locked', models.PositiveIntegerField(default=0, editable=False, verbose_name='locked')),
                ('swap_total', models.PositiveIntegerField(default=0, editable=False, verbose_name='swap_total')),
                ('swap_free', models.PositiveIntegerField(default=0, editable=False, verbose_name='swap_free')),
                ('dirty', models.PositiveIntegerField(default=0, editable=False, verbose_name='dirty')),
                ('write_back', models.PositiveIntegerField(default=0, editable=False, verbose_name='write_back')),
                ('annon_pages', models.PositiveIntegerField(default=0, editable=False, verbose_name='annon_pages')),
                ('mapped', models.PositiveIntegerField(default=0, editable=False, verbose_name='mapped')),
                ('shmem', models.PositiveIntegerField(default=0, editable=False, verbose_name='shmem')),
                ('slab', models.PositiveIntegerField(default=0, editable=False, verbose_name='slab')),
                ('sreclaimable', models.PositiveIntegerField(default=0, editable=False, verbose_name='sreclaimable')),
                ('sunreclaimable', models.PositiveIntegerField(default=0, editable=False, verbose_name='sunreclaimable')),
                ('kernelstack', models.PositiveIntegerField(default=0, editable=False, verbose_name='kernelstack')),
                ('pagetables', models.PositiveIntegerField(default=0, editable=False, verbose_name='pagetables')),
                ('nfs_unstable', models.PositiveIntegerField(default=0, editable=False, verbose_name='nfs_unstable')),
                ('bounce', models.PositiveIntegerField(default=0, editable=False, verbose_name='bounce')),
                ('writebacktemp', models.PositiveIntegerField(default=0, editable=False, verbose_name='writebacktemp')),
                ('commit_limit', models.PositiveIntegerField(default=0, editable=False, verbose_name='commit_limit')),
                ('commit_as', models.PositiveIntegerField(default=0, editable=False, verbose_name='commit_as')),
                ('malloc_total', models.PositiveIntegerField(default=0, editable=False, verbose_name='malloc_total')),
                ('malloc_used', models.PositiveIntegerField(default=0, editable=False, verbose_name='malloc_used')),
                ('malloc_chunk', models.PositiveIntegerField(default=0, editable=False, verbose_name='malloc_chunk')),
            ],
        ),
    ]
