# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-07 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0025_hardware_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware_data',
            name='userid',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, verbose_name='user'),
        ),
    ]
