# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-11 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0028_auto_20191009_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowunfollowdetails',
            name='share_medium',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='share_medium'),
        ),
    ]
