# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-18 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0029_userfollowunfollowdetails_share_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytimespend',
            name='timestamp',
            field=models.DateTimeField(null=True, verbose_name='timestamp'),
        ),
    ]
