# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-19 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0030_activitytimespend_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetails',
            name='userid',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='user'),
        ),
    ]
