# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-14 23:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_spirit', '0031_videodetails_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_email', models.CharField(max_length=30, verbose_name='contact_email')),
                ('description', models.TextField(blank=True, null=True)),
                ('feedback_image', models.CharField(max_length=255, verbose_name='contact_email')),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
