# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-15 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0032_userfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='by_user',
        ),
        migrations.DeleteModel(
            name='UserFeedback',
        ),
    ]
