# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-11 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0035_auto_20191119_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='contact_number',
            field=models.CharField(default=b'', max_length=30, verbose_name='contact_number'),
        ),
    ]
