# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-08 01:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0036_userfeedback_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjarvisdump',
            name='android_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='android_id'),
        ),
        migrations.AlterField(
            model_name='userjarvisdump',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
