# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-18 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0039_auto_20200618_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='state',
        ),
    ]
