# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-30 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0040_auto_20200618_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='title')),
                ('s3_file_path', models.CharField(blank=True, max_length=1000, null=True, verbose_name='s3 file path')),
                ('image_path', models.CharField(blank=True, max_length=1000, null=True, verbose_name='image path')),
                ('author_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='author name')),
            ],
        ),
    ]
