# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-10 01:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0041_musicalbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjarvisdump',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='created_at'),
        ),
    ]
