# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-11 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0042_userjarvisdump_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjarvisdump',
            name='dump_type',
            field=models.CharField(blank=True, choices=[(b'1', b'user_activities_data'), (b'2', b'error_logs'), (b'3', b'hardware_info')], max_length=50, null=True, verbose_name='dump_type'),
        ),
    ]
