# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-25 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0043_auto_20200711_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicalbum',
            options={'ordering': ['order_no']},
        ),
        migrations.AddField(
            model_name='musicalbum',
            name='language_id',
            field=models.CharField(blank=True, choices=[(b'0', b'All'), (b'1', b'English'), (b'2', b'Hindi'), (b'3', b'Tamil'), (b'4', b'Telugu'), (b'5', b'Bengali'), (b'6', b'Kannada'), (b'7', b'Malayalam'), (b'8', b'Gujarati'), (b'9', b'Marathi'), (b'10', b'Punjabi'), (b'11', b'Odia'), (b'12', b'Bhojpuri'), (b'13', b'Haryanvi'), (b'14', b'Sinhala')], default=b'1', max_length=10, null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='musicalbum',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last_modified'),
        ),
        migrations.AddField(
            model_name='musicalbum',
            name='order_no',
            field=models.PositiveIntegerField(default=0, verbose_name='order_no'),
        ),
    ]
