# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-31 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0044_auto_20200725_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='popup_img_url',
            field=models.TextField(blank=True, null=True, verbose_name='Popup Image URL'),
        ),
    ]
