# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-31 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0045_campaign_popup_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='show_popup_on_app',
            field=models.BooleanField(default=False),
        ),
    ]
