# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-08-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0046_campaign_show_popup_on_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Campaign Details'),
        ),
    ]
