# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-26 19:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0050_auto_20201110_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[b'0'], size=None),
        ),
    ]
