# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-17 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0050_auto_20201110_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaserecordcount',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='databaserecordcount',
            name='update_time',
            field=models.PositiveIntegerField(default=60, verbose_name='Update Time'),
        ),
    ]
