# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-28 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0051_auto_20201117_2140'),
        ('drf_spirit', '0051_campaign_languages'),
    ]

    operations = [
    ]
