# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-13 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_spirit', '0053_auto_20201128_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='UserMusicReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='drf_spirit.MusicAlbum')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='drf_spirit.MusicReport')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
