# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-12 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0053_auto_20201128_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbum',
            name='is_extracted_audio',
            field=models.BooleanField(default=False, verbose_name='Is Extracted Audio'),
        ),
    ]
