# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-13 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0054_musicalbum_is_extracted_audio'),
        ('drf_spirit', '0054_musicreport_usermusicreport'),
    ]

    operations = [
    ]
