# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-12-28 18:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_spirit', '0055_merge_20201213_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicreport',
            name='target',
            field=models.CharField(blank=True, choices=[(b'video', b'Video'), (b'music', b'Music'), (b'user', b'User'), (b'general', b'General')], default=b'general', max_length=30, null=True, verbose_name='Target'),
        ),
        migrations.AddField(
            model_name='usermusicreport',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='usermusicreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermusicreport',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum_topic.Topic'),
        ),
        migrations.AlterField(
            model_name='usermusicreport',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='drf_spirit.MusicAlbum'),
        ),
    ]
